version: '3.5'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    container_name: sonarqube
  db:
    build:
      context: postgres/
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    volumes:
    - postgresql:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data
    container_name: postgres
  jenkins-master:
    build:
      context: jenkins-master/
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-master
    volumes:
      - jenkins_home:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
  jenkins-slave:
    build:
      context: jenkins-slave/
    container_name: jenkins-slave
    restart: always
    environment:
      - JENKINS_URL=http://jenkins-master:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
      - home_jenkins:/home/jenkins # Avoid mysql volume mount issue
    depends_on:
      - jenkins-master 
volumes:
  jenkins_home:
    name: jenkins_home
    driver: local
  home_jenkins:
    name: home_jenkins
    driver: local
  sonarqube_conf:
    name: sonarqube_conf
    driver: local
  sonarqube_data:
    name: sonarqube_data
    driver: local
  sonarqube_extensions:
    name: sonarqube_extensions
    driver: local
  sonarqube_bundled-plugins:
    name: sonarqube_bundled
    driver: local
  postgresql:
    name: postgresql
    driver: local
  postgresql_data:
    name: postgresql_data
    driver: local
